export const ADD_LOCATION = 'ADD_LOCATION';
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const CLEAR_ALL_LOCATIONS = 'CLEAR_ALL_LOCATIONS';
export const UPDATE_LOCATIONS = 'UPDATE_LOCATIONS';
export const UPDATE_LOCATION_DATA = 'UPDATE_LOCATION_DATA';
export const LOCATION_WEATHER_DATA = 'LOCATION_WEATHER_DATA';
export const RESET_NEW_LOCATION = 'RESET_NEW_LOCATION';
export const RESET_LOCATION_DATA = 'RESET_LOCATION_DATA';